services:
  db:
    image: postgres:latest
    container_name: inventory-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=inventory
    ports:
      - "5433:5432"